### ISSUE TITLE
Database access from outside possible by default

### ISSUE THREAD

**Issue by nikolas-beckel** [Dokploy/dokploy#100]
Hello, I have created a redis database and by default it is accessible from the outside via port 6379. I would have rather expected the behavior that this is not possible by default and only applications within the Docker network (or dokploy project) could access it.

In my case, this is specified under "External Credentials", whereby port 6379 is a placeholder in the input, not actually filled in by me.
![image](https://github.com/Dokploy/dokploy/assets/15029707/6ae73196-6f0f-4401-a9e9-133d8e25f8e2)

I have not yet been able to discover where and how I can set that the redis database is not accessible externally.
Is this behavior intentional or is it a bug?

**Comment by Siumauricio** [comment]
Thank you, for reporting this problem, it is indeed a minimal error we had at the time of creating the redis database that we use internally to manage the deployments, several people asked me this on discord and I think your question finally I knew why it was happening.

But if the error you get when assigning 6379 is because we already use that port as I mentioned in the redis database we use, but this will be fixed in the next version, thanks!
