### ISSUE TITLE
Toast indicates success even for failed deployments

### ISSUE THREAD

**Issue by buti1021** [Dokploy/dokploy#118]
Hey just checking out your work and really like it so far.

However, stumbled over something while testing. My application deployment failed, however the toast said it succeeded. Took me a bit to figure out that I can click on the deployment pane to see how/if the deployment worked.

Steps to reproduce:

1. Create a project
2. Create an application
3. Add a publicly available docker image that does not require auth and specify some username+password, e.g. bitnami/express:latest
test test
4. Deploy

Deployment will fail but toast will indicate success

Relevant code:
https://github.com/Dokploy/dokploy/blob/113df9ae12c37095addd5484bae7e8f614adbcfc/components/dashboard/application/general/deploy-application.tsx#L61

I think there are more or less two options to make this a little more intuitive:

1. Wait with toast until the result of the deployment is known and then give a precise success or error toast.
4. Change text of the current toast to something like: "Deployment started successfully, check the deployment view for the result of the deployment"

Best!

**Comment by Siumauricio** [comment]
Few Things:

1. the image you shared is an existing image so it is somewhat valid for you to get a toaster success.
2. If you use incorrect credentials to try to download a public image you will get errors.
3. If for some reason suppose the docker image needs Y or X thing and it fails because it needs that thing, the image will run anyway, why? because all dockerhub images are valid images.

I think that the implementation that we have is correct works well, that case that you gave me works and there is no error, suddenly we will be able to improve the UX to show a spinner or something like that although in fact we already show it in the buttons and also in the status which turns yellow denoting that it is running, it can suddenly be confusing if you suddenly see 2 toasters at the same time podriamos mejorar eso de alguna forma
