### ISSUE TITLE
Exposing Port 3001 in Docker Container for Node.js Application

### ISSUE THREAD

**Issue by freidev** [Dokploy/dokploy#18]
Hello,

I want to thank you for the excellent work you've done. Currently, I'm running a Node.js application on port 3001, but this port hasn't been exposed by Docker. I'd like to know how I can expose this port so I can use domains and assign the container port.

Thank you in advance for your help

![Screenshot 2024-05-01 at 12 08 54 PM](https://github.com/Dokploy/dokploy/assets/54672897/6780453c-559a-4d5e-9ab7-0aa8c2f08948)

**Comment by Siumauricio** [comment]
Hi,

You don't need to expose the port manually. Simply navigate to the 'Domains' section and add a new domain. You'll see an option for 'Container Port'—set this to `3001`. Traefik will automatically handle the redirection of the domain to the container.

**Comment by freidev** [comment]
Hello,
Thank you for the excellent work you've done. I've realized that the issue is related to AWS, as I haven't been able to configure AWS and Cloudflare to use domains yet, I think about permission issues.

Any recommendation?

**Comment by freidev** [comment]
Specifically, the error it gives is:
ERR_TOO_MANY_REDIRECTS

**Comment by Siumauricio** [comment]
@freidev your domain is on cloudflare?

I remembed had the same issue, but is not related to dokploy is about cloudflare itself since they give the SSL certificate so there is some conflict, so you need to set the following: 
This is my config
![Screenshot 2024-05-01 at 2 00 22 PM](https://github.com/Dokploy/dokploy/assets/47042324/965ff2bb-e0e1-45a6-a64e-432e5370eef5)

**Comment by freidev** [comment]
Thank you, you are a genius. Indeed that was the problem.
Now I will be able to contribute to this great project. 🚀

**Thanks** again ❤️
