### ISSUE TITLE
Support pgvector

### ISSUE THREAD

**Issue by sangdth** [Dokploy/dokploy#218]
### What problem will this feature address?

The need for pgvector is quite popular

### Describe the solution you'd like

Have to install using app, quite cumbersome compare to Postgres feature

### Describe alternatives you've considered

Right now I have to setup using App, and many repetitive setup like POSTGRES_DB, POSTGRES_USER etc

**Comment by Siumauricio** [comment]
Hello, I would like to know pgvector is not a plugin or something specific for postgres? I think they do not offer any graphical interface as such that fits the template concept, correct If I'm wrong.

**Comment by sangdth** [comment]
I am not expert in pgvector, but I guess their Dockerfile ship the Postgres instance WITH the vector extension by default.

Currently I'm using Dokploy app with their Docker setting and setting env variables. Then I can connect to it with `postgresql://...` like normal Postgres database.

**Comment by Siumauricio** [comment]
Got it, in this case I'll sugest to use the dedicated postgres database, and when you create the database specify the docker image `ankane/pgvector:v0.5.1`, I recommend to use this approach since postgres dedicated offers backups and you can have more control than in the case we implement this as a docker compose template

![image](https://github.com/user-attachments/assets/1db3e0a3-1cc5-4e12-9971-5d1cabb67f92)

**Comment by sangdth** [comment]
Wow this is great, I will try this way! Thanks so much @Siumauricio

**Comment by juliomuhlbauer** [comment]
Wouldn't be better if we could add extensions like Supabase?

**Comment by Qbason** [comment]
@Siumauricio This will not work for pgvector where postgresql version is bigger or equal than 18.
It's because the mount path is different, but the actual pattern match doesn't cover this case, see: https://github.com/Dokploy/dokploy/pull/3048/changes
For example I would like to use this version: 
pgvector/pgvector:pg18-bookworm 
and I am getting error.
