### ISSUE TITLE
Change default port 3000

### ISSUE THREAD

**Issue by icebob** [Dokploy/dokploy#29]
Hello,

great project. However, how can I change the Dokploy web port 3000 to another one? 
I tried to find it in "Web server settings" on the site but I didn't find it.

**Comment by jlucaso1** [comment]
Try to change the env var `PORT`

**Comment by icebob** [comment]
But how, I installed the containers with the `curl ....sh | sh` command.

**Comment by icebob** [comment]
I would like to use it in localhost for dev tools, but my main project is running on 3000 as well and it causes conflict at port binding.

**Comment by Siumauricio** [comment]
You have two options.

1. change the port that you application are using this is more simple.
2. You don't need to add explicity a port in `Ports Section`, just simply add a new domain and in the container port set the 3000 port and that's all, you can have any applications running in 3000 port because when you add a domain traefik automatically will redirect to the container, but if you want to use the application without a domain and you want to explicity bind to a port just go to ports and target port set 3000 and published set something like 3001

**Comment by Siumauricio** [comment]
@icebob Give me more details about this, if you want hit me up on discord and I will be delighted to help you
