### ISSUE TITLE
Markdown support for project/app description

### ISSUE THREAD

**Issue by exi66** [Dokploy/dokploy#328]
### What problem will this feature address?

Better quality of life. This will allow you to describe the service in more detail, for example, a link to documentation or a repository.

**Comment by predragnikolic** [comment]
Hello,

The challenging part is:
- finding a good rich tech editor 
- usually a rich text editor really increases the bundle size
- deal with 2-3 bugs that usually occur when adding a rich text editor
- GitHub, and most sites that have projects for the description field use plain text

To sum up my thoughts, I would not find a huge benefit if such feature existed. Rich text editors are good for, blog posts, product description, comments... But got  short description for projects, not so much.

**Comment by exi66** [comment]
yes, there are really a lot of problems with the editor, but in my opinion a lightweight parser without an editor would be enough.
Like [marked](https://www.npmjs.com/package/marked) or [markdown-it](https://www.npmjs.com/package/markdown-it)

**Comment by Siumauricio** [comment]
I agree with the points of @predragnikolic, it makes a lot of sense I think implementing this I don't see much value, because why would you want to describe an application? for certain templates it is necessary to have instructions although I think you can use simpler approaches for that case, so at this time I don't see much value in adding this functionality.

**Comment by Siumauricio** [comment]
I will close this issue because this is not part of something that dokploy has to take care of. If in the future we need something like this we can reopen, thanks.
