### ISSUE TITLE
Is dokploy not supporting Raspberry Pi?

### ISSUE THREAD

**Issue by aliahadmd** [Dokploy/dokploy#35]
![image](https://github.com/Dokploy/dokploy/assets/90032081/e26cea37-3d29-4ae6-80f8-50c79c04b879)

**Comment by aliahadmd** [comment]
I am using Ubuntu server in Raspberry Pi 4B device.

**Comment by centopw** [comment]
Check PR #37 someone already working on it

**Comment by Siumauricio** [comment]
Looks like nextjs didn't updated this package [@next/swc-android-arm64 package](https://www.npmjs.com/package/@next/swc-android-arm64) since 13.2.4 which serve specifically for arm/v7 builds and in the current project we use version 14+, so I need to downgrade the project to next 13 in order to support builds for this architecture here is the open issue on nextjs side https://github.com/vercel/next.js/issues/58483.
