### ISSUE TITLE
support soketi

### ISSUE THREAD

**Issue by mutou981** [Dokploy/dokploy#354]
### What problem will this feature address?

support tmplate https://docs.soketi.app/getting-started/installation/docker

### Describe the solution you'd like

- Support env
- Support https/wss(certificate)

### Describe alternatives you've considered

x

**Comment by Nathanjms** [comment]
Apologies if I'm posting this in the wrong place, but I've been trying unsuccessfully to configure Soketi today and was wondering if you have any guidance on it if you have used it?

I can connect to the http(s) version of the url, but trying to connect to the web sockets version results in an error. I've tried with a custom domain and also just an auto-generated one.

I suspect traefik is changing it to https instead of wss, but am unsure what the solution is here as it's my first time looking at traefik.

Would appreciate any guidance here if possible, thanks!
