### ISSUE TITLE
stop deploy is not effective.

### ISSUE THREAD

**Issue by hubingkang** [Dokploy/dokploy#390]
### To Reproduce

"stop deploy" is not effective. I can't terminate Deployments, it keeps running without ending. And even when I redeploy deploy, it still exists.

### Current vs. Expected behavior

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/502e0bca-d4c7-40db-ac4c-9b3a1d307f12">

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/6d52421c-bca1-4ea2-91f0-64cb3c2d113b">

when I redeploy dokploy, it still exists.

<img width="1323" alt="image" src="https://github.com/user-attachments/assets/bbc3e09f-8ea7-4b85-b611-4fc91929fbbc">

### Provide environment information

```bash
Dokploy: v0.7.1
```

### Which area(s) are affected? (Select all that apply)

Application, Docker

**Comment by Siumauricio** [comment]
This is not a bug, also we don't have an option to cancel the running deployment, the option we have is to cancel the incoming deployments this is because we use queues for deployments, but in your case seems probably your vps has freeze or restarted and that makes you have running deployments but in fact they are not running they are just in running status, so when you make more deployments the running deployments will dissapear

**Comment by lzw10168** [comment]
```bash
docker restart <DOKPLOY_CONTAINER_ID>
```

can resolve it
