### ISSUE TITLE
Containers running on worker not shown in Dokploy

### ISSUE THREAD

**Issue by mpcref** [Dokploy/dokploy#470]
### To Reproduce

Deploy a container to a worker node.

### Current vs. Expected behavior

When the deployment is done I see that the container is running on the worker node with `docker ps` and that it was indeed started at the time of deployment.
But it's nowhere to be found in Dokploy.
I expect to be able to:

1. Connect to the container from the General tab via "Open terminal"
2. See metrics in the Monitoring tab
3. See the container listed in the Logs tab
4. See the container listed in the Docker tab

None of this is working. It looks as though Dokploy didn't deploy anything even though it did.

### Provide environment information

```bash
Rocky Linux release 9.4 (Blue Onyx)
Docker v27.2.1
Dokploy v0.8.3
```

### Which area(s) are affected? (Select all that apply)

Docker

**Comment by Siumauricio** [comment]
Hi @mpcref, This is the expected behavior, if you deploy replicas for `logs` internally we use `docker logs` instead of `docker service logs` which serves for docker swarm specifically but atm we don't use that probably when we Implement #281 we will show the logs and containers from others nodes, the monitoring and access to the terminal is not possible when deploying replicas on external server also docker swarm doesn't offer the feature out of the box, for now this is the expected behavior, if you have any other questions feel free to re-open.

**Comment by mpcref** [comment]
As mentioned on Discord, please make sure the UI clearly communicates that this is not supported. Because now it just looks like its broken. There's also no overview in Dokploy to see which services are running on which nodes. (or which nodes are hosting which services) so logically I start looking at the places mentioned above where I also can't see any trace of these services. So if you're new to Dokploy (as I currently am) you will think Dokploy didn't deploy the service.

**Comment by timbo-tj** [comment]
+1 that it looks broken...!

**Comment by dcalsky** [comment]
Shot, wasting my 2 hours to troubleshoot this problem, I thought it's my configuration fault...

**Comment by timbo-tj** [comment]
Yeah it is extremely misleading. There are a couple of different bits of UI that really could use a warning in Swarm mode. ("These stats/details/info is for this node only. It does not represent stats/details/info of other nodes in the swarm.")
