### ISSUE TITLE
Deployments get stuck

### ISSUE THREAD

**Issue by egoist** [Dokploy/dokploy#508]
### What problem will this feature address?

After a git push, dokploy creates multiple deployments which get stuck at Docker building phrase, I don't know how exactly this happened

![CleanShot 2024-10-01 at 00 06 05@2x](https://github.com/user-attachments/assets/7f09a097-1a67-4b4d-b8eb-af649f13a6f7)

### Describe the solution you'd like

Allow me to cancel the ongoing deployments, otherwise it will show 'Running' forever even after I restart my VPS

### Describe alternatives you've considered

I haven't found a workaround

**Comment by Siumauricio** [comment]
Hi @egoist,
Thank you for reporting this, this is the expected behavior for now.


your server may restart due to `docker` usually when you build an application with docker it is possible that your machine restarts or starts to freeze this is due to the high ram consumption caused by docker, there are 2 options to never have this problem again, the usage of dokploy itself is very low.

1. Increase your vps resources (which I don't think you want to do).
2. Build your image in a ci/cd on github and push to dockerhub, and dokploy ui will only download and run the image and will no longer have to build the image which can cause instability.
 
I would recommend the second option is the easiest one in fact it is the one I follow to deploy the docs and the website to prevent that case that docker freeze the vps.

I have 2 actions https://github.com/Dokploy/dokploy/blob/canary/.github/workflows/deploy.yml#L24

which pushes to my dokploy server and you can also make push on deploy easily doing this https://github.com/Dokploy/dokploy/issues/164#issuecomment-2190980695 or just attaching the webhook url that is in deployments tab and paste in to dockerhub


![image](https://github.com/user-attachments/assets/e8eec621-e90d-40c0-8ba3-28959b282f8f)
![image](https://github.com/user-attachments/assets/0845947a-a8db-4b68-b05a-a4b3a17b78d7)


> ------------------------------------------------------------

Referring to your deployments that appear running and are below, they are not running just stayed in that state due to the restart, as you do more deployments will disappear, one way I think to solve this is that it would be that when dokploy restarts check all deployments that are running and mark them as error or staled

btw Very fan of your work @egoist, I'm glad you are trying the product and using it!

**Comment by egoist** [comment]
Building the image on CI is indeed the way to go, thanks for the clarification. It would be great to include examples of GitHub Actions and GitLab CI config in the documentation as well. 👍
