### ISSUE TITLE
The traefik labels get duplicated if I have two services and two domains in one docker compose file

### ISSUE THREAD

**Issue by callmewhy** [Dokploy/dokploy#533]
### To Reproduce

1. deploy docker compose via raw compose.yml file
2. define two services with two different domains binded
3. deploy

### Current vs. Expected behavior

Current: the endpoint has 50% change to get failed. The previewed docker compose file show there are two duplicate labels for each service
expected: deduplicate labels. it's deduplicated if I click the refresh button. but back to duplicate after deployment.

### Provide environment information

```bash
OS: ubuntu 24
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Additional context

<img width="929" alt="image" src="https://github.com/user-attachments/assets/3a64cd44-e729-48bc-ac08-94a45900de95">

**Comment by Siumauricio** [comment]
This is the expected behavior, so always make sure to click refresh on the preview compose, that will be the actual compose that will be executed.

If you added domains and deployed, and then try to see the preview compose, you will see that the labels are duplicated, but it is because it is basically reading the file with the labels that were previously modified + the domain labels, so you need to click refresh to see the real compose that will be executed.

**Comment by callmewhy** [comment]
it's ok to click refresh after adding domains. but how about auto-deploy? is it better to deduplicate automatically as it's easy to detect
