### ISSUE TITLE
Install error: 1/1 mkdir /var/lib/docker: read-only file system

### ISSUE THREAD

**Issue by adelpro** [Dokploy/dokploy#55]
I'm trying to install using
`curl -sSL https://dokploy.com/install.sh | sh`
I get this error:
`1/1 mkdir /var/lib/docker: read-only file` system
- im on the root user
- im on ubuntu server v22
- i have docker already installer .

**Comment by mosessmax** [comment]
hey there, so going by what you said, you already have docker installed, check the permissions for the /var/lib/docker folder using this command  `ls -ld /var/lib/docker` to see the kind of permissions you currently have, because i'm guessing that's the issue

if you see anything other than `drwx--x--- 12 root root 4096 DATE TIMESTAMP /var/lib/docker` then there's a problem, you have a bit of permission issues, you should be able to fix it with this command

`sudo chown -R root:root /var/lib/docker`
`sudo chmod -R 755 /var/lib/docker`

then restart the server or just maybe restart docker  with`sudo systemctl restart docker`

**Comment by adelpro** [comment]
same error, this is what I get when I run the command `ls -ld /var/lib/docker`

```
root@ubunto:~# ls -ld /var/lib/docker
drwxr-xr-x 2 755 root 4096 May  6 13:02 /var/lib/docker
```

**Comment by adelpro** [comment]
@Siumauricio 
1- Yes i have already installed docker before running the install command ( im using docker for other things)

2- im running Ubuntu server on a local pc and accessing it using ssh

**Comment by Siumauricio** [comment]
can you try this ?

1. sudo su
2. curl -sSL https://dokploy.com/install.sh | sh

**Comment by adelpro** [comment]
> can you try this ?
> 
> 1. sudo su
> 2. curl -sSL https://dokploy.com/install.sh | sh

I tried, same error

**Comment by Siumauricio** [comment]
My only recomendation to avoid this issue permissions is start from a fresh installation, because this clearly is Docker issues which doesn't have the right access to docker enviroment because you already had docker installed

**Comment by Siumauricio** [comment]
Have you found a solution for this @adelpro ?
Can you reinstall docker?

**Comment by adelpro** [comment]
> Have you found a solution for this @adelpro ?
> Can you reinstall docker?
> 

Unfortunately i can't reinstall docker i have other containers up and running.
I tried to stop docker service, the installation of Dokploy was completed with no errors, but after restarting the docker service, i didn't find the Dockploy container.

**Comment by adelpro** [comment]
I finally installed, my docker was installed on ubuntu server using snap, i uninstalled docker then re-installed using the official documentation ([link here](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository))
Then i used the official install script to install Dockploy [(linkhere)](https://dokploy.com/)

**Comment by Siumauricio** [comment]
Glad to hear that, any related errors you can open another issue, thank you!
