### ISSUE TITLE
Self hosted gitlab

### ISSUE THREAD

**Issue by PasVegan** [Dokploy/dokploy#560]
### What problem will this feature address?

Currently the install button redirect to gitlab.com when the application is created

### Describe the solution you'd like

Be able to connect to a self hosted gitlab instance

### Describe alternatives you've considered

The only workaround is to use git

**Comment by Siumauricio** [comment]
This sounds good, we would have to add a url to specify the gitlab instance and by default it would be gitlab.com

**Comment by codihaus** [comment]
This, acctually a quick update, can you please consider this in the next release @Siumauricio ? How can we help? We can assign team member to to this feature.

**Comment by Siumauricio** [comment]
I'm open to PR's @codihaus, if you are down to create a PR would be awesome, I don't have time to work on this feature for now

**Comment by codihaus** [comment]
Can you please briefly explain the flows and the file name I should look at?

I understand we would need to create another field, but how about when we actually pull the source code, we need to pass the gitlab_url to them, right?

**Comment by Nidrux** [comment]
Any updates on this issue? If none I would like to look into this.

**Comment by A-D-E** [comment]
I have the same problem, is there at least a URL pattern that could be entered manually?

**Comment by Siumauricio** [comment]
I think this would not work just changing the url since we use gitlab applications and internally we use oauth to download the repositories, I don't know if there is any limitation with gitlab self hosted, I have opened a pr draft with the necessary changes except the change when we clone the repository we use oauth2, if someone wants to take it back I am open to changes, basically this is all done just need to test and change the url of the cloning process.

https://github.com/Dokploy/dokploy/pull/835/files#diff-a7f765f5570440bb5ce865404cfddddc26671aa1c7d75ff9cdd0e943e33533c5R353-R354

**Comment by dardarwail** [comment]
Hello,

I’m trying to use a self-hosted GitLab instance without HTTPS. When I attempt to build the project, I encounter the following error in the logs:

`fatal: unable to access 'https://<my-ip>/username/myproject.git/': server certificate verification failed. CAfile: none CRLfile: none`

This is expected since, as mentioned, my self-hosted GitLab does not use HTTPS.

Does anyone have any suggestions or solutions?

**Comment by codihaus** [comment]
Because we're calling server-server, I suspect that your certificate is not a fullchain API (intermediate, ca, cert).
Can you please gimme your address? I will double check and help you to resolve.

**Comment by dardarwail** [comment]
I want to work without a certificate, meaning I’m using an insecure scheme for my managed GitLab instance. As a result, there’s no use of full-chain, intermediate certificates, CA, or cert files. My self-hosted GitLab is running on a private IP address with an insecure scheme.

Initially, the project is cloned successfully, as shown in the logs:

```
success: Initializing deployment  
success: Cloning Repo myip/username/myproject.git to /etc/dokploy/applications/backend-oljpdo/code: ✅  
success: Cloning into '/etc/dokploy/applications/backend-oljpdo/code'...  
```

However, after the first successful cloning, I encounter an error:

```
fatal: unable to access 'https://myip/username/myproject.git/': server certificate verification failed. CAfile: none CRLfile: none  
ERROR Cloning: Error: Cloning into '/etc/dokploy/applications/backend-oljpdo/code'...  
fatal: unable to access 'https://myip/username/myproject.git/': server certificate verification failed. CAfile: none CRLfile: none  
❌  
```

Why does it try to access the repository via HTTPS after the first successful clone? Any help resolving this issue would be greatly appreciated!
