### ISSUE TITLE
Dokploy API or cli

### ISSUE THREAD

**Issue by qvdp** [Dokploy/dokploy#57]
Hello,

First of all thank you for this amazing shared work, I've successfully installed Dekploy on two different servers & deployed a small micro service system on both servers, and it's working flawlessly

I am curious if there are any plans to offer an API or CLI for interacting with Dokploy instances, specifically for updating application deployments during CI/CD processes like GitHub actions or GitLab CI.

Thank you

**Comment by Siumauricio** [comment]
Thank you! That's a good feature request I need to think about it how we can reuse or create specific endpoints to be available trought the cli.

For now let's leave open!

**Comment by qvdp** [comment]
> Thank you! That's a good feature request I need to think about it how we can reuse or create specific endpoints to be available trought the cli.
> 
> For now let's leave open!

Thank you for considering this @Siumauricio .

I am eager for this implementation. In your experience with the project, what do you consider the best approach for automating application release deployments?

Personally, I rely on tagged Docker images to deploy my various applications, and sometimes I use git tags, never branches commits.

**Comment by Siumauricio** [comment]
You use dockerhub to push your images? if so you can use the webhook URL in the deployments tab and paste in to dockerhub webhooks, and when you make a new release it automatically will trigger a new deployment

**Comment by qvdp** [comment]
> You use dockerhub to push your images? if so you can use the webhook URL in the deployments tab and paste in to dockerhub webhooks, and when you make a new release it automatically will trigger a new deployment

You mean using a `latest` tag ?

On my side, I use a scaleway docker registry, I will check if they provide a similar feature or if I can implement such a behaviour in my CI/CD jobs.

**Comment by hikinine** [comment]
@Siumauricio  
What are your ideas for this implementation? 

I think release an public api for a existing SaaS is awesome but without a really nice design, can be really painful the long term.
Dokploy will include `API key based authentication`? 
Maybe consider including `nestjs`?

Benefits to include nestjs to the public api
1 - Endpoint versioning
2 - Easier documentation generation (like swagger)
3 - Easier way to add and control rate limiting, observability, etc 

Since this public api will only proxy the TRPC api that is already in production. Maybe NestJS would be too much just for exposing some endpoints. 

Anyway, let me know your thoughts
Ill be happy to be part of this feature.

**Comment by Siumauricio** [comment]
@hikinine You are right, I don't think we are going to handle a versioning api because that is going to be really painful eventually instead we are going to use versioning and we have to specify which version of the cli is compatible with dokploy, using nestjs in my opinion is too much, in fact we can reuse some trpc endpoints and then also add some additional endpoints to be available through the cli, to be honest i have some ideas, but as you said it has to be easy to understand and not be complicated just like dokploy works, simple and easy to use that's the most paramount thing not to be confusing

If you are really interested to work with me send me a message in discord and we can make brainstorm to think how we can make this feature and thanks! https://discord.gg/crzwW5JA
