### ISSUE TITLE
Postgres Database Restarts Unexpectedly.

### ISSUE THREAD

**Issue by jordanopos** [Dokploy/dokploy#61]
Deploying Postgres service with Dokploy. Everything works fine in the start but after some time (about 7 hours or so) the database logs always shows that it's receiving a fast shutdown request. Then the database is deleted and the service starts again. Tried to make a new one twice, same result.

Here are the server logs.
<img width="1107" alt="Screenshot 2024-05-08 at 12 25 50" src="https://github.com/Dokploy/dokploy/assets/66879794/d3632b2c-dbbf-4bad-be27-c19a6536f221">

Also noticed it keeps making new containers. Not only for Postgres but for all the services.
<img width="1256" alt="Screenshot 2024-05-08 at 12 30 10" src="https://github.com/Dokploy/dokploy/assets/66879794/ebe0ee9a-0872-45c3-8080-a3323ad9694c">

Not sure if it's an issue with persistence or my config. Any help would be much appreciated.

**Comment by Siumauricio** [comment]
Very weird behavior, since we don't touch anything besides creating the service, I will create a postgres database and see if i can reproduce

**Comment by Siumauricio** [comment]
After hours, nothing seems strange, the instance is still running


![Screenshot 2024-05-08 at 11 37 17 PM](https://github.com/Dokploy/dokploy/assets/47042324/6894293f-dea2-41ab-917b-057437344b4b)

**Comment by jordanopos** [comment]
Thanks for checking this out.
I don't have any backups enabled. Just installed on a new digital ocean droplet. Could the issue be somehow related to digital ocean infrastructure?

I've checked the latest instance of another service. You can see it exited twice prematurely before starting again.

<img width="1297" alt="Screenshot 2024-05-09 at 12 05 44" src="https://github.com/Dokploy/dokploy/assets/66879794/9cbfa943-c97f-4d41-8fd2-e6ae93a60a4c">

Here are the server logs for the exited container.

<img width="1212" alt="Screenshot 2024-05-09 at 12 10 36" src="https://github.com/Dokploy/dokploy/assets/66879794/181de4d2-5220-4cfa-8756-14877446d030">

**Comment by Siumauricio** [comment]
all looks like good, again when you make a new deployment, rebuild or something a new container will be created, so that's why you see multiples containers as exited is not a bug is how docker swarm works under the hood, if you want to delete the duplicated exited containers, you can go to settings -> space -> and then clean stopped containers

You can replicate this bevahior, simply make a new deployment and you will see how it creates a new container this apply to applications and databases.


Look i have a database running for 7 days and zero issues
![Screenshot 2024-05-09 at 9 49 39 AM](https://github.com/Dokploy/dokploy/assets/47042324/552decb4-d53e-42e6-ac16-ab20c8692966)
![Screenshot 2024-05-09 at 10 15 58 AM](https://github.com/Dokploy/dokploy/assets/47042324/efee9812-3aa2-4554-9f91-07a6f337fb5e)

**Comment by jordanopos** [comment]
Thanks for the clarification. Are there any circumstances that can trigger the postgres database to be redeployed automatically?.

**Comment by Siumauricio** [comment]
Since we use docker swarm, it automatically will restart on failure.

But in your case nothing seems wrong, so you don't have to worry about it

**Comment by jordanopos** [comment]
Alright. Undertood. I'll keep monitoring the situation to try and see if anything is wrong on my end. Thanks for your help. Cheers.
