### ISSUE TITLE
WebSocket pending for minutes after container starts

### ISSUE THREAD

**Issue by ddahan** [Dokploy/dokploy#611]
### To Reproduce

I'm having trouble to get logs of my application in Dokploy UI

1. Step 1: I go to "Logs" tabs, nothing happens

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/0f96812e-ecf7-4137-8178-1ddc6291844f">

2. Opening a chrome inspector, I can see that a WS request is made with pending state, and no messages are exchanged:
<img width="1176" alt="image" src="https://github.com/user-attachments/assets/2bd90f44-ddb6-4be0-bb4b-598b6c3cd3ef">

<img width="577" alt="image" src="https://github.com/user-attachments/assets/f69f1683-5ef4-4d6c-b714-0d7f3037b232">

In the meantime, I can absolutely run a `docker logs <my-container>` with no issue.

3. Weirdly, after a long period of time (like 3 or 4 minutes), logs are eventually displayed, request is not pending anymore and has a `101` response:

<img width="924" alt="image" src="https://github.com/user-attachments/assets/6d00becf-e4f6-445d-8330-26535a562c1e">

<img width="785" alt="image" src="https://github.com/user-attachments/assets/0b089a43-4703-4acd-9c52-6e7262b9dc39">

At this point, everything works as expected. But as soon as I restart my container, I need to wait for long minutes before the websocket connection works.

### Current vs. Expected behavior

Having logs (and WS connection) works immediately.

### Provide environment information

```bash
OS : Debian GNU/Linux 12 (bookworm) (x86)
Dokploy v0.10.3
VPS Provider: Vultr
Trying to deploy a fastAPI webserver with gunicorn (with Docker compose)
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

It seems it happens on Brave (Chrome), but not on Safari.

In addition, I think that when Dokploy is trying to reach this URL, it's a bug:

<img width="474" alt="image" src="https://github.com/user-attachments/assets/4ba4dbe2-4773-469d-aaa9-b9f5a72accdb">

However, it does not seem to have a direct impact.

**Comment by Siumauricio** [comment]
Thanks for reporting this

 it is very rare this problem happens when you reload the page or open many times a section where websockets are used.

I had solved it for the deployments logs but I see that this is blocked in general, a solution for now is to open another window of your browser and log in and it will work or if not after about 25 minutes it will reset in the browser you had the problem.

at the moment I don't have a solution for this, several weeks ago I was trying to fix this because I already knew about it but I'm still looking for a solution or know what I'm doing wrong, I'll take a look again!

**Comment by ddahan** [comment]
Thanks for the quick reply!
I was wondering if I did something wrong. Glad I didn't :) As it was my first try with Dokploy, I initially thought nothing worked at all, until I ssh on my VPS and noticed everything's fine. Then I realize it was "just" a WS issue in inspector.

> I had solved it for the deployments logs

In some cases, I had the same issue with deployment logs. And monitoring too. Basically, every WS connection I guess. However it seems I don't have the issue at all with Safari. (I'm using Brave/Chrome usually).

Let me know if I can help by testing a patch or anything like this.
Good luck with this!

**Comment by Siumauricio** [comment]
After a few hours looks like this issue is very specific to Brave(I'm using also as my default browser)

I tested on Chrome, Edge, Safari and it works without issues I tried to reload alot of times the website and is working however in brave when you try to do that it will become the conection as pending so I assume something is happening on brave specifically

I think the code is fine I just think is a issue specifically from brave

**Comment by Siumauricio** [comment]
For now I'm pretty sure this issue is not related to dokploy itself is more a browser issue specifically <<BRAVE>>
