### ISSUE TITLE
Rebuild does not pull "latest" container

### ISSUE THREAD

**Issue by Silbad** [Dokploy/dokploy#683]
### To Reproduce

A container with latest version

### Current vs. Expected behavior

Hi,

I'm a bit worried that the rebuild button only seems to do a simple deploy.
=> the latest images don't work

To fix everything, I have to put the version in place of latest.

Otherwise I love Dokploy, great application! ❤️

### Provide environment information

```bash
Ubuntu: 22.04
Dokploy: 0.11.0
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by Silbad** [comment]
So no, sorry, I think they're two different problems. There's a problem with the :latest container that can be solved by replacing with the version.
But I do have another problem with a redirection conflict between one container and the other...

**Comment by Siumauricio** [comment]
Try to use `pull_policy `

```yaml
services:
    myservice:
        image: an-image
        pull_policy: always
```

**Comment by Siumauricio** [comment]
feel free to reopen if you have any other questions or use the discussions to ask for help, thanks.

**Comment by haikali3** [comment]
thank you so much i was having so much trouble because it was the old docker image yet the --build from dokploy override it and the compose doesnt have  Clear Cache toggle.

<img width="364" height="101" alt="Image" src="https://github.com/user-attachments/assets/912d8578-31d3-4d58-9738-4a997a279389" />
