### ISSUE TITLE
Auto-deploy doesn't work when connecting a GitHub organization.

### ISSUE THREAD

**Issue by artem-kostylev** [Dokploy/dokploy#741]
### To Reproduce

Create an organization, add a private repository to it, connect it to Dokploy, and then try pushing a change.

### Current vs. Expected behavior

Proper functioning of auto-deploy

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 24.04
Dokploy version: 0.10.10
VPS Provider: Linode
What applications/services are you tying to deploy?
Backend with Docker and Nextjs App
```

### Which area(s) are affected? (Select all that apply)

Application, Docker

**Comment by henriklovhaug** [comment]
I think you still have to set the webhook url in the settings of the Github repository.

**Comment by Siumauricio** [comment]
No, when you deploy via GitHub it should automatically deploy on push, are you sure are you using GitHub provider ?

**Comment by artem-kostylev** [comment]
> No, when you deploy via GitHub it should automatically deploy on push, are you sure are you using GitHub provider ?

<img width="1390" alt="Screenshot 2024-11-20 at 8 09 39 PM" src="https://github.com/user-attachments/assets/ce5eeff7-a021-4208-9ee7-cbadd12b574e">

Yes, Could it be because my Dokploy panel has basic auth?

**Comment by Siumauricio** [comment]
You answered the question yourself I think 😅, I just tried it and it works.

**Comment by airtonix** [comment]
> You answered the question yourself I think 😅, I just tried it and it works.

What was the answer? 

To not have auth required to access the dokploy dashboard? 

1. how is that acceptable? 
2. what does that even have to do with how github clients connect and recieve events from github apps installed into repos?

**Comment by sauravtom** [comment]
this still doesnt work for me

**Comment by thobiasn** [comment]
Just chiming in here since others experiencing this might be something along the same lines as what I just experienced.
I setup a new application and pointed it to my github repo. After pushing to master no deployment started.

Looking at the github application that dokploy created when i added my github account I noticed webhook errors. Turns out I was blocking github from my cloudflare security rules. Adding an exception for github here fixed the issue for me. Below is a few instructions that might help others debug their specific issue.

In dokploy:
- Go to git
- Follow the link to the github app from your connection (see screenshot)

<img width="1056" height="546" alt="Image" src="https://github.com/user-attachments/assets/bfdb2395-8f67-41ef-8f62-b353a618b423" />

In github: (after following the link)
- Go to the advanced tab
- Check for failed deliveries and inspect the request logs (see screenshot)

<img width="1108" height="591" alt="Image" src="https://github.com/user-attachments/assets/c8b8ffe1-b8d8-47d3-b088-3a0fbdd8e866" />

Hope this can help others having issues with their deployments.
