### ISSUE TITLE
Job Task Never Finish.

### ISSUE THREAD

**Issue by juandl** [Dokploy/dokploy#770]
### To Reproduce

I notice that sometimes maybe 1 task is taking too long (maybe pulling the image) and lets say you hit "deploy" again, 2 tasks go to "schedule", the last task executed finish first but the other gets stuck and never finishes. Because of this is not possible to deploy anything else, and the task never gets removed. 

Cancel Queues doesn't remove the task

![image](https://github.com/user-attachments/assets/580b32be-b2ef-4184-a276-b47155e7d6ad)

### Current vs. Expected behavior

Maybe a way to "kill any process" should be a good option to avoid this issue. 

### Provide environment information

```bash
Ubuntu 24 LTS.
Dokploy Version: v0.12.0
```

### Which area(s) are affected? (Select all that apply)

Application, Docker

**Comment by Siumauricio** [comment]
Are you deploying on remote server?

Cancel queues only remove the incoming jobs not the current ones

**Comment by m0d16l14n1** [comment]
Hello. Got the same issue with autodeploy. 

Always need to wait for much time and it will 50/50 never finish. Need to cancel all the queues and deploy manually. And it will work like a charm. Deploying docker-compose. 

Never got that issue before, it's appeared on 0.12.0 > previously was sitting long on something "10".

![image](https://github.com/user-attachments/assets/d2255a15-6344-44cb-87d9-134b2aa1eb51)

I will try to update to latest version one more time and update, if it's fixed/not.

**Comment by juandl** [comment]
@Siumauricio Local server, haven't try remote

**Comment by m0d16l14n1** [comment]
Have no issues on latest version, now it's working like it was before

**Comment by Siumauricio** [comment]
I don't know if you were using nixpacks, but if so it seems that in the last version there was a problem I set the version to 1.29.1, 

Some reason why certain builds can get stuck in running and never finish, it may be because of certain configurations suddenly with bun happens a lot that the docker builds get stuck and never finish and the process just dies, I do not think it is a problem of dokploy itself as the problem may be due to external factors as I mentioned, you can be the package manager among other things.

Feel free to reopen if you have a minimal reproduce!
