### ISSUE TITLE
Verbatim copy (plagiarism?) of CapRover

### ISSUE THREAD

**Issue by githubsaturn** [Dokploy/dokploy#78]
Congrats on the launch!

There are many issues with the licensing and terms and conditions that suggest verbatim copy of CapRover.

![image](https://github.com/Dokploy/dokploy/assets/10582082/562ea72d-8893-489c-b1fd-e28b47a16abd)
![image](https://github.com/Dokploy/dokploy/assets/10582082/09d4305b-12ec-4132-ad20-b277b348240a)

Also, website mentions this software is free and open source for all usecases, but the license mentions:
- No reselling of Dokploy
- Limitation on commercial distribution
- Paid features of Dokploy (I briefly looked and Dokploy doesn't seem to offer any paid features)

While getting ideas are totally fine, the verbatim copy isn't something that is appreciated.

PS: maintainer of CapRover

**Comment by Siumauricio** [comment]
Hi.

First of all, thank you.

Second, with the license it is something that you cannot go against what I think, whatever I want to do or what I say.

And yes, of course, without a doubt, I took that same idea adding some extra clauses, but if it bothers you so much, I can paraphrase it and that's it.

**Comment by githubsaturn** [comment]
> yes, of course, without a doubt, I took that same idea

No. you absolutely did not take ideas. You took it word by word as in my screenshot. And got back to me with saying:
> but if it bothers you so much, I can paraphrase it and that's it.

I suggest looking up plagiarism and paraphrasing. Not going to continue this conversation.

Your project looks awesome, but I am here to educate.

**Comment by Siumauricio** [comment]
> No. you absolutely did not take ideas. You took it word by word as in my screenshot. And got back to me with saying:

I don't know why you bother, it's so logical that you don't know that a terms and conditions license structure is practically identical in many projects with minor differences. look this whas the original file https://www.diffchecker.com/9uW6Ou1o/


> I suggest looking up plagiarism and paraphrasing. Not going to continue this conversation.

and it is not plagiarism, plagiarism is literally an exact copy without modifying which I did not do, and I don't see anything wrong here since your license allows modification.

All good with you, I know your project is one of the pioneers in this, that's why I told you I'll modify it and the problem goes away.
