### ISSUE TITLE
Error After Mounting Physical Volume: 'No such container: select-a-container'

### ISSUE THREAD

**Issue by Rekwian** [Dokploy/dokploy#906]
### To Reproduce

1. Start a container using a standalone Docker image (Application service).
2. Mount a physical volume from the server to Docker (e.g., /src/data/project/public/documents → /app/public/documents).
3. Make a change to the environment variables or any configuration.
4. Deploy the changes or try to reload the container.

### Current vs. Expected behavior

What happens:
- The container stops but never restarts after a reload.
- Changes (e.g., environment variable updates) are not applied.
- The error No such container: select-a-container appears.

Expected behavior:
- The container should reload and restart successfully.
- Changes to the environment variables or configurations should apply correctly.

### Provide environment information

```bash
* OS: Debian 12.8
* Dokploy: v0.15.0
* Docker image: Custom Dockerfile from PHP:7.2-fpm-alpine
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

- I am not using Docker Compose, only a standalone Docker image.
- The issue consistently happens when mounting physical volumes from the server to Docker (e.g., /src/data/project/public/documents → /app/public/documents), error disappear when I remove the volumes.
- This behavior breaks both reload and deploy functionalities.

### Will you send a PR to fix it?

No

**Comment by Siumauricio** [comment]
It is not a bug, it is simply that if you mount an invalid path or directory, your application will not start and you will get `No such container: select-a-container appears`.

check here: https://docs.dokploy.com/docs/core/troubleshooting#mounts-are-causing-my-application-not-to-run

Currently I have not found a way to display an error before the application is executed since we use the docker api directly, if you are open to send a PR, I will accept it.
